image: gcc

stages:
  - compile
  - test

compile:
  stage: compile
  before_script: 
    - apt update && apt -y install make autoconf 
  script: make
  artifacts:
    paths:
    - build/alraune
    expire_in: 20 minutes
  cache:
    paths:
    - "*.o"

test:
  stage: test
  script: make tests
